version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: banco_postgres_container
    environment:
      POSTGRES_DB: banco_postgres
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5431:5432"
    restart: always
